In [1]:
import numpy as np

In [22]:
a = np.array([[1,1,2],[0,1,2],[3,5,6]])
print np.linalg.matrix_rank(a)
print a

3
[[1 1 2]
 [0 1 2]
 [3 5 6]]


In [4]:
b = np.eye(2,3)
print b

[[1. 0. 0.]
 [0. 1. 0.]]


In [5]:
c = np.ones((5,2))
print c

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [9]:
d = np.arange(1,13,2).reshape(3,2)
print d

[[ 1  3]
 [ 5  7]
 [ 9 11]]


In [12]:
a = np.eye(4,5)
print type(a[[0,3], [1,3]])

<type 'numpy.ndarray'>


In [14]:
print np.linalg.det(a)

-3.999999999999999


In [17]:
w, v = np.linalg.eig(a)
print w,v

[ 8.30328514  0.55880272 -0.86208786] [[-0.28760248 -0.77762528 -0.32091962]
 [-0.25296529  0.61396651 -0.69317823]
 [-0.9237388  -0.13544018  0.64537938]]


In [18]:
print a.T

[[1 0 3]
 [1 1 5]
 [2 2 6]]


In [19]:
print a.T

[[1 0 3]
 [1 1 5]
 [2 2 6]]


In [20]:
print np.transpose(a)

[[1 0 3]
 [1 1 5]
 [2 2 6]]


In [21]:
print np.transposenp.transpose(a)

[[1 0 3]
 [1 1 5]
 [2 2 6]]
